version: 2.1

jobs:
  build_default:
    shell: /bin/bash
    environment:
      CONTAINER_NAME: quay.io/redsift/sandbox-go-rocksdb
      GO_V: 1.13.5
      ROCKSDB_V: 5.18.3
    docker:
      - image: cibuilds/docker:18.06.3-ce
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $QUAY_USER -p $QUAY_PASS quay.io
      - run: ./docker_build
      - run: docker push $CONTAINER_NAME

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build_default:
          context: org-global
